--
-- PostgreSQL database dump
--

-- Dumped from database version 11.14 (Debian 11.14-0+deb10u1)
-- Dumped by pg_dump version 11.14 (Debian 11.14-0+deb10u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: jogador; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.jogador (
    id integer NOT NULL,
    nome character varying
);


ALTER TABLE public.jogador OWNER TO postgres;

--
-- Name: jogador_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.jogador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jogador_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partida; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partida (
    id integer NOT NULL,
    data_hora timestamp without time zone,
    jogador1_id integer,
    jogador2_id integer,
    jogador3_id integer,
    jogador4_id integer,
    placar1 integer,
    placar2 integer
);


ALTER TABLE public.partida OWNER TO postgres;

--
-- Name: partida_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partida ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partida_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: jogador; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.jogador VALUES (1, 'Marcos Batista');
INSERT INTO public.jogador VALUES (2, 'Rômulo (vovô)');
INSERT INTO public.jogador VALUES (3, 'Raoni (B)');
INSERT INTO public.jogador VALUES (4, 'Wellison (Zezo)');
INSERT INTO public.jogador VALUES (5, 'Wellington');
INSERT INTO public.jogador VALUES (7, 'Arruda (Mução)');
INSERT INTO public.jogador VALUES (8, 'Miguel');
INSERT INTO public.jogador VALUES (9, 'Wagner');
INSERT INTO public.jogador VALUES (10, 'Jefter');
INSERT INTO public.jogador VALUES (11, 'Cavalcanti');
INSERT INTO public.jogador VALUES (12, 'Gomes');
INSERT INTO public.jogador VALUES (13, 'Joaquin');
INSERT INTO public.jogador VALUES (14, 'Medeiros');
INSERT INTO public.jogador VALUES (15, 'Sub Evangelista ');
INSERT INTO public.jogador VALUES (16, 'Possidio');
INSERT INTO public.jogador VALUES (17, 'Costa neto');
INSERT INTO public.jogador VALUES (6, 'Othun ( Cap )');


--
-- Data for Name: partida; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.partida VALUES (5, '2025-05-26 15:19:00', 1, 11, 6, 12, 0, 5);
INSERT INTO public.partida VALUES (7, '2025-05-26 15:26:00', 11, 5, 6, 12, 4, 1);
INSERT INTO public.partida VALUES (10, '2025-05-26 15:33:00', 13, 1, 3, 8, 1, 3);
INSERT INTO public.partida VALUES (11, '2025-05-26 15:38:00', 10, 16, 11, 15, 3, 2);
INSERT INTO public.partida VALUES (12, '2025-05-26 15:40:00', 6, 12, 3, 8, 2, 3);
INSERT INTO public.partida VALUES (9, '2025-05-26 18:32:00', 11, 15, 2, 14, 3, 0);
INSERT INTO public.partida VALUES (13, '2025-05-26 15:44:00', 2, 14, 3, 8, 4, 0);
INSERT INTO public.partida VALUES (14, '2025-05-26 15:50:00', 16, 10, 1, 4, 0, 3);
INSERT INTO public.partida VALUES (15, '2025-05-26 15:50:00', 1, 4, 6, 12, 0, 3);
INSERT INTO public.partida VALUES (6, '2025-05-26 18:25:00', 15, 11, 2, 14, 1, 3);
INSERT INTO public.partida VALUES (17, '2025-05-26 15:56:00', 3, 8, 6, 12, 2, 4);
INSERT INTO public.partida VALUES (18, '2025-05-26 15:59:00', 10, 16, 2, 14, 2, 3);
INSERT INTO public.partida VALUES (19, '2025-05-26 16:03:00', 8, 3, 14, 2, 3, 1);
INSERT INTO public.partida VALUES (20, '2025-05-26 16:04:00', 6, 15, 1, 4, 1, 3);


--
-- Name: jogador_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.jogador_id_seq', 17, true);


--
-- Name: partida_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partida_id_seq', 20, true);


--
-- Name: jogador jogador_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.jogador
    ADD CONSTRAINT jogador_pkey PRIMARY KEY (id);


--
-- Name: partida partida_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT partida_pkey PRIMARY KEY (id);


--
-- Name: partida fk_jogador1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT fk_jogador1 FOREIGN KEY (jogador1_id) REFERENCES public.jogador(id);


--
-- Name: partida fk_jogador2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT fk_jogador2 FOREIGN KEY (jogador2_id) REFERENCES public.jogador(id);


--
-- Name: partida fk_jogador3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT fk_jogador3 FOREIGN KEY (jogador3_id) REFERENCES public.jogador(id);


--
-- Name: partida fk_jogador4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partida
    ADD CONSTRAINT fk_jogador4 FOREIGN KEY (jogador4_id) REFERENCES public.jogador(id);


--
-- PostgreSQL database dump complete
--

